package ru.netcracker.belyaev.enums;

public enum GameCases {
	GO,
	INSIDE_WALL,
	OUTSIDE_WALL,
	RIVER,
	KILLED,
	INJURED,
	SHOT,
	FIND_TREASURE,
	UP_TREASURE,
	DROP_TREASURE,
	FIND_MAGE,
	PREDICTION_REAL,
	PREDICTION_FAKE,
	UNDER_ARCH,
	EXIT_FROM_MAZE,
	EXIT_WITH_REAL_TREASURE,
	EXIT_POINT,
	GAME_OVER,
	CURRENT_PLAYER_INFORMATION
}
